In [1]:
import pandas as pd
import re
import requests
from bs4 import BeautifulSoup

In [2]:
response = requests.get('https://web-scraping-demo.zgulde.net/news')
soup = BeautifulSoup(response.text)

In [3]:
articles = soup.select('.grid.gap-y-12 > div')

In [7]:
summary = article.p.text

NameError: name 'article' is not defined

In [13]:
def parse_news_article(article):
    title = article.h2.text
    date, author = article.select('.italic')[0].find_all('p')
    summary = article.find_all('p')[-1]   
    return {'title': title, 'date': date.text, 'author': author.text, 'summary': summary.text}

In [14]:
     response = requests.get('https://web-scraping-demo.zgulde.net/news')
     soup = BeautifulSoup(response.text)
     articles = soup.select('.grid.gap-y-12 > div')
     pd.DataFrame([parse_news_article(article) for article in articles])

,title,date,author,summary
0,evening process range,1981-02-07,By Traci Jackson,Happy letter get miss later without. Bed envir...
1,why Mrs either,1974-04-07,By Richard Green,Congress prepare dream teach down speak tradit...
2,reduce shake might,2000-08-10,By Erin Mcmahon,Line begin forward such best spend member. Fac...
3,consumer carry who,2000-01-26,By Brian Foley,Involve situation black wonder by. Leg forward...
4,study draw book,1979-04-16,By Eric Hall,Drive brother save itself class sport understa...
5,fast opportunity employee,1972-09-08,By Richard Summers,Yet research life field environment social sit...
6,affect focus same,1982-07-08,By Todd Smith,Card to number charge this. Account operation ...
7,human measure along,1983-01-01,By Rachel Martin,Water no box. Site phone make. Budget policy i...
8,simply street each,1983-08-26,By Justin Hardin,Conference yourself reality identify. Hour deg...
9,many worry law,2020-09-01,By Todd Henry Jr.,Move direction common financial. Last scene fi...
10,really food stop,2017-03-10,By Janice Howard,Discuss water participant owner. Management im...
11,walk sure three,1983-01-09,By Brandi Carpenter,Feeling wear seem they give not. Prevent almos...

In [65]:
def get_person_info(article):
    name = article.h2.text
    quote = article.find_all('p')[0]
    email = article.find_all('p')[1]
    ph_number = article.find_all('p')[2]
    address = article.find_all('p')[-1]
     
    return {'name': name, 'quote': quote.text.strip(), 'email': email.text, 'ph_number': ph_number.text, 'address': address.text.strip()}

In [73]:
    response = requests.get('https://web-scraping-demo.zgulde.net/people')
    soup = BeautifulSoup(response.text)
    articles = soup.select('.person')
    #articles = soup.select('div', attrs = {'id':'people'})
    pd.DataFrame([get_person_info(article) for article in articles])

,name,quote,email,ph_number,address
0,Calvin Miller,"""Virtual even-keeled pricing structure""",denisemorton@ross.net,650-355-4690,24030 Jackson Roads \n South Do...
1,Zachary Rangel,"""Switchable fault-tolerant moderator""",michellepayne@hotmail.com,+1-598-491-1615x991,825 Arnold Trail Suite 066 \n O...
2,Jacqueline Larsen,"""Open-source 24hour complexity""",stewartheather@yahoo.com,306.059.2377,43489 Mclean Walk Suite 466 \n ...
3,Joy Alvarado,"""Triple-buffered empowering standardization""",brittany87@gmail.com,001-132-328-4442x4690,33485 Johnson Park \n Lake Andr...
4,Amanda Waters,"""Switchable dedicated focus group""",fsmall@brooks.info,(549)792-3762,417 Perkins Wells \n Fishermout...
5,Patrick Carter,"""Fully-configurable tertiary data-warehouse""",iwilliams@hotmail.com,+1-693-018-5551x50091,507 Michael Fields \n Stevensbo...
6,Erica Solomon,"""Quality-focused value-added synergy""",stacywilliams@rodriguez-woodard.com,(391)159-2126x8592,8924 Meghan Stream \n New Kimbe...
7,Katie Jones,"""Configurable non-volatile open system""",matthew93@gmail.com,001-425-235-3389,97234 Kimberly Union Apt. 756 \n ...
8,Ann Hurley,"""Operative exuding flexibility""",arthurbryant@anderson.com,193.918.4805x47887,8117 Park Well Suite 974 \n Joh...
9,Julie Heath,"""Multi-tiered attitude-oriented capability""",tfox@wilson.org,351-932-1433x2597,60574 Dominique Mission Suite 349 \n ...

In [75]:
#soup.select('#people')
#this code snippet doesn't work bc it finds every single record instead of one that repeats over and over.

In [45]:
soup.select('.person')

[<div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">Regina Nixon</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Open-architected methodical attitude"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">qray@carter.info</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">001-392-930-5188x825</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 42417 Fowler Junctions Suite 825 <br/>
                 Dawnside, DE 69818
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">Tara Gillespie</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Right-sized value-added budgetary management"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">kelleymichael@gmail.com</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">+1-907-421-0785x30237</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 294 Richard Track <br/>
                 Martinchester, ME 94609
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">William Hahn</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Vision-oriented high-level collaboration"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">ortizmorgan@hotmail.com</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">(597)236-6920</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 4741 Scott Divide <br/>
                 North Janice, VA 94497
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">Megan Williams</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Stand-alone bottom-line protocol"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">meganblair@yahoo.com</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">917.502.3781x41134</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 14771 Kenneth Run <br/>
                 North Jenniferport, OK 55150
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">Sabrina Nelson</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Up-sized systemic info-mediaries"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">simmonstheodore@hotmail.com</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">798.850.0965x4764</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 993 Timothy Parkway <br/>
                 East Lawrenceburgh, AR 21747
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">Larry Hernandez</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "User-centric intermediate strategy"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">amber97@chavez.net</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">001-659-668-9026x2451</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 21469 Jones Isle <br/>
                 South Jennifer, NV 73503
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">Stephanie Carpenter</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Innovative multi-tasking instruction set"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">rochafelicia@hotmail.com</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">(866)612-8631</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 078 Anderson Crescent <br/>
                 North Charles, PA 37379
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">Robert Rose</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Team-oriented asynchronous intranet"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">masseysarah@kennedy.biz</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">001-565-242-2789x73479</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 1912 Tracey Villages <br/>
                 South Jacobside, IL 55502
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">John Ibarra</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Reduced next generation attitude"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">dunntracey@gmail.com</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">133.874.3997</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 8096 Morris Meadows Apt. 187 <br/>
                 Port Alex, VT 05427
             </p>
 </div>
 </div>,
 <div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
 <h2 class="text-2xl text-purple-800 name col-span-full border-b">Mary Acosta</h2>
 <p class="quote col-span-full px-5 py-5 text-center text-gray-500">
             "Automated non-volatile artificial intelligence"
         </p>
 <div class="grid grid-cols-9">
 <i class="bi bi-envelope-fill text-purple-800"></i>
 <p class="email col-span-8">christinesantos@benjamin.com</p>
 <i class="bi bi-telephone-fill text-purple-800"></i>
 <p class="phone col-span-8">088-220-3782</p>
 </div>
 <div class="address grid grid-cols-9">
 <i class="bi bi-geo-fill text-purple-800"></i>
 <p class="col-span-8">
                 3645 Bates Gateway Suite 804 <br/>
                 North Brett, CO 26393
             </p>
 </div>
 </div>]

In [46]:
soup.select('.person')[0]

<div class="person border rounded px-3 py-5 grid grid-cols-2 gap-x-3 bg-purple-50 hover:shadow-lg transition duration-500">
<h2 class="text-2xl text-purple-800 name col-span-full border-b">Regina Nixon</h2>
<p class="quote col-span-full px-5 py-5 text-center text-gray-500">
            "Open-architected methodical attitude"
        </p>
<div class="grid grid-cols-9">
<i class="bi bi-envelope-fill text-purple-800"></i>
<p class="email col-span-8">qray@carter.info</p>
<i class="bi bi-telephone-fill text-purple-800"></i>
<p class="phone col-span-8">001-392-930-5188x825</p>
</div>
<div class="address grid grid-cols-9">
<i class="bi bi-geo-fill text-purple-800"></i>
<p class="col-span-8">
                42417 Fowler Junctions Suite 825 <br/>
                Dawnside, DE 69818
            </p>
</div>
</div>

In [47]:
people = soup.select('.person')

In [49]:
person = people[0]

In [50]:
person.h2.text

'Regina Nixon'

In [52]:
person.p.text.strip()

'"Open-architected methodical attitude"'

In [54]:
person.select('.email')[0].text

'qray@carter.info'

In [58]:
person.select('.phone')[0].text

'001-392-930-5188x825'

In [59]:
person.select('.address')[0].text.strip()

'42417 Fowler Junctions Suite 825 \n                Dawnside, DE 69818'

In [69]:
#person.find_all('p')[1].text  
#This also finds the email

'qray@carter.info'

In [70]:
#person.find_all('p')[2].text
#This also finds the phone

'001-392-930-5188x825'

In [72]:
#person.find_all('p')[-1].text.strip()
#This also finds the address

'42417 Fowler Junctions Suite 825 \n                Dawnside, DE 69818'